/*
    This file has been generated by Connect SDK Wizard.
    Copyright (c) 2020 Ingram Micro. All Rights Reserved.
*/
using connect;
using connect.models;


class ChangeAssetFlow : Flow
{
    public ChangeAssetFlow()
    : base(request => ((AssetRequest)request).type == "change")
    {
        this.step("Fail request", _ => this.FailChange());
    }


    public void FailChange()
    {
        this.fail("Cannot process request of type \"change\".");
    }
}
