/*
    This file has been generated by Connect SDK Wizard.
    Copyright (c) 2020 Ingram Micro. All Rights Reserved.
*/
using connect;
using connect.api;
using connect.logger;


class Processor
{
    public static void Main(string[] args)
    {
        // Log level is set to debug. Never use this level when in production!
        Env.initLogger(new LoggerConfig().level(Logger.LEVEL_DEBUG));

        // Process asset requests
        new connect.Processor()
            .flow(new PurchaseAssetFlow())
            .flow(new ChangeAssetFlow())
            .processAssetRequests(new Query()
                .equal("asset.product.id__in", Env.getConfig().getProductsString())
                .equal("status", "pending"));
    }
}
