# This file has been generated by Connect SDK Wizard.
# Copyright (c) 2020 Ingram Micro. All Rights Reserved.

from connect import Flow


class ChangeAssetFlow(Flow):
    def __init__(self):
        super().__init__(lambda request: request.type == 'change')
        self.step('Fail request', fail_request)

    def fail_change(self):
        self.fail('Cannot process request of type "change".')
